janbarari/gradle-analytics-plugin

build.gradle.kts, gradle/libs.versions.toml
> R-8
Project build scripts dependency management migrated to `gradle version catalogs`
=> [R-8] Migrate to version catalogs

.github/pull_request_template.md
> N-9
According to have clear PR with our own standards, pull request template will help us to create better PRs
=> [N-9] Github pull request template file

codecov.yml, src/main/kotlin/io/github/janbarari/gradle/analytics/core/gradlebuild/GradleBuildImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/core/logger/Logger.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/core/logger/LoggerImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/plugin/GradleAnalyticsPlugin.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/plugin/PluginModule.kt, src/test/kotlin/io/github/janbarari/gradle/analytics/core/logger/LoggerTest.kt
> F-13
Creating a custom logger will let us to control the log visibility when project scale
Create a custom logger with tests
Logger package has 100% Code Coverage
=> F-13/Add Logger

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/TotalBuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/TotalBuildReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/CreateTotalBuildMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/CreateTotalBuildMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/CreateTotalBuildReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/RenderTotalBuildReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/UpdateTotalBuildMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/totalbuild/UpdateTotalBuildMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/resources/index-template.html, src/main/resources/totalbuild-metric-template.html
> F-27
Total Build Metric Feature Implemented.
=> F-27/Total Build metric feature implemented

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModuleMethodCount.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModuleMethodCountReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModulesMethodCountMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModulesMethodCountReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/create/CreateModulesMethodCountMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/create/CreateModulesMethodCountMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/report/CreateModulesMethodCountReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/report/RenderModulesMethodCountStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/update/UpdateModulesMethodCountMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesmethodcount/update/UpdateModulesMethodCountMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/resources/index-template.html, src/main/resources/modules-method-count-metric-template.html, src/main/resources/res/styles.css, src/test/kotlin/io/github/janbarari/gradle/analytics/data/DatabaseRepositoryTest.kt
> F-30
What if project owners could see which modules have more methods than others, How much percent of the project methods are owned by the module, and how much percent of the module methods increased or decreased during the period of time.
This metric lets the project owners:
Estimate when to change the team size of the different modules.
Estimate when to break the module into multiple modules.
Guess the build-time cache invalidation effect for each module.
Tested on a real project for all scenarios
No data
Single data
Multiple data
=> F 30/implement modules method count metric

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/TaskInfo.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt, src/test/kotlin/io/github/janbarari/gradle/analytics/domain/model/TaskInfoTest.kt
> P-31
Task cache status are not available inside the TaskInfo data class. try to find a way to add this data
=> build cache information added in model

src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsTask.kt
> H-33
[Issue-26](https://github.com/janbarari/gradle-analytics-plugin/issues/26)
A message will be shown to the user about the empty data
Tested on the local machine(weak test)
=> H-33/fix_no_data_crash

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/BuildInfo.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/DependencyResolveMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/DependencyResolveReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/create/CreateDependencyResolveMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/create/CreateDependencyResolveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/report/CreateDependencyResolveReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/report/RenderDependencyResolveReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/update/UpdateDependencyResolveMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencyresolvemetric/update/UpdateDependencyResolveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/extension/BuildMetricExtensions.kt, src/main/resources/configuration-metric-template.html, src/main/resources/dependencyresolve-metric-template.html, src/main/resources/execution-metric-template.html, src/main/resources/index-template.html, src/main/resources/initialization-metric-template.html
> F-36
Represents the average time spent for resolving, and downloading the dependencies in each build.
=> F-36/Dependency resolve metric implemented

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/SuccessBuildRateMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/SuccessBuildRateReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/successbuildrate/create/CreateSuccessBuildRateMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/successbuildrate/report/CreateSuccessBuildRateReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/successbuildrate/report/RenderSuccessBuildRateReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/successbuildrate/update/UpdateSuccessBuildRateMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsTask.kt, src/main/kotlin/io/github/janbarari/gradle/extension/BuildMetricExtensions.kt, src/main/resources/success-build-rate-metric-template.html, src/test/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/SuccessBuildRateMetricJsonAdapterTest.kt, src/test/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/SuccessBuildRateReportJsonAdapterTest.kt, src/test/kotlin/io/github/janbarari/gradle/extension/BuildMetricExtensionsTest.kt
> F-39
This type of plugin result should be read by someone that knows data science, they need some accurate metrics like Mean, Median, Mode and etc.
Mean and Median are available for the Success build rate metric.
`reportAnalytics` Gradle task output had a long message. It's refactored.
Not yet.
=> refactor: analyticsReport gradle task output

detekt-config.yml, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModuleDependency.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/ModulesDependencyGraph.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/ModulesDependencyGraphMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesDependencyGraphReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/create/CreateModulesDependencyGraphMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/create/CreateModulesDependencyGraphMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/report/CreateModulesDependencyGraphReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/report/RenderModulesDependencyGraphReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/update/UpdateModulesDependencyGraphMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/update/UpdateModulesDependencyGraphMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/DependencyGraphGenerator.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/ScannerUtils.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt, src/main/resources/index-template.html, src/main/resources/modules-dependency-graph-metric-template.html, src/test/kotlin/io/github/janbarari/gradle/analytics/scanner/BuildExecutionLogicTest.kt
> F-40
Having well architecture modules dependency graph will help the developers to optimize the project builds. and optimize the connection between the modules.
Implemented with Mermaid JS.
=> Add Modules Dependency Graph Metric

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/ModuleBuildHeatmap.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/ModulesBuildHeatmapMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModuleBuildHeatmap.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesBuildHeatmapReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesMethodCountReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesSourceCountReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesTimelineReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/create/CreateModulesBuildHeatmapMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/create/CreateModulesBuildHeatmapMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/render/CreateModulesBuildHeatmapReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/render/RenderModulesBuildHeatmapReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/update/UpdateModulesBuildHeatmapMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/update/UpdateModulesBuildHeatmapMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulestimeline/render/RenderModulesTimelineReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/extension/ListExtensions.kt, src/main/resources/index-template.html, src/main/resources/modules-build-heatmap-template.html, src/main/resources/res/styles.css
=> F 41/add modules build heatmap metric

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/Dependency.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/DependencyDetailsMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/DependencyDetailsReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/create/CreateDependencyDetailsMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/create/CreateDependencyDetailsMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/render/CreateDependencyDetailsReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/render/RenderDependencyDetailsReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/update/UpdateDependencyDetailsMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/dependencydetails/update/UpdateDependencyDetailsMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsTask.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/ScannerUtils.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt, src/main/kotlin/io/github/janbarari/gradle/extension/GradleExtensions.kt, src/main/kotlin/io/github/janbarari/gradle/extension/ListExtensions.kt, src/main/resources/dependency-details-metric-template.html, src/main/resources/index-template.html, src/test/kotlin/io/github/janbarari/gradle/analytics/scanner/BuildExecutionLogicTest.kt
=> [F-41] Add dependency details metric

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/ModulesSourceSizeMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesSourceSizeReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/create/CreateModulesSourceSizeMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/create/CreateModulesSourceSizeMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/report/CreateModulesSourceSizeReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/report/RenderModulesSourceSizeStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/update/UpdateModulesSourceSizeMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/update/UpdateModulesSourceSizeMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/resources/index-template.html, src/main/resources/modules-source-count-metric-template.html, src/main/resources/modules-source-size-metric-template.html
> F-44
Modules source size could be a good metric to understand when need to break a module codebase
=> Add modules source size metric

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/BuildMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/metric/ModulesCrashCountMetric.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/ModulesCrashCountReport.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/report/Report.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/usecase/SaveMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/create/CreateModulesCrashCountMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/create/CreateModulesCrashCountMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/render/CreateModulesCrashCountReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/render/RenderModulesCrashCountReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/update/UpdateModulesCrashCountMetricStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulescrashcount/update/UpdateModulesCrashCountMetricUseCase.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulessourcesize/report/RenderModulesSourceSizeReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/resources/index-template.html, src/main/resources/modules-crash-count-metric-template.html
> F-45
Watching modules crash happen times could be a good metric when a project manager want to see the CI crash causes in the team.
=> Add modules crash count metric

docs/donation.md, docs/setup.md, docs/stylesheets/extra.css, docs/third-party.md, mkdocs.yml
> R-70
- Documentation dark mode added
- Some minor typo issues fixed
- Third-party section added
The codebase wasn't affected.
=> R-70/refactor docs darkmode thirdparty

src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/BuildInfo.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/domain/model/TimeSlot.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsTask.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt, src/main/kotlin/io/github/janbarari/gradle/utils/MathUtils.kt, src/main/resources/index-template.html, src/main/resources/modules-timeline-metric-template.html, src/main/resources/res/functions.js, src/main/resources/res/styles.css, src/test/kotlin/io/github/janbarari/gradle/analytics/domain/model/BuildInfoTest.kt
> F-71
Yaaayy, the dark mode feature has been added to the report.
- Add dark mode to report
- Fix `reportAnalytics` task compatibility issue with Gradle configuration-cache. [HotFix]
- Optimize Configuration, Dependency Resolve, and Execution process measurement.
=> F 71/add report dark mode

docs/community.md, mkdocs.yml
> N-11
Discord channel will help the plugin community stay in touch together.
- Discord invitation link added in README file
- Discord invitation link added in Documentation page
No need to test
=> N-11/add discord channel

docs/setup.md, src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPlugin.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPluginConfig.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/ScannerUtils.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt
> F-75
[Issue-45](https://github.com/janbarari/gradle-analytics-plugin/issues/45)
```
Plugin is great, so thanks for putting this out.  
I'm thinking that I want to have this run for me locally (configured by a gradle.properties value)  
but not for the rest of my team at this point. Be nice to have a way to enable / disable the plugin  
so it doesn't do anything such as the summary unless its enabled (i.e. it can be configured, but won't run)
```
new property `isEnabled` added in the plugin configuration so that the user can switch it. 
- Feature Added
- Documentation `setup.md` updated
=> F-75/enable-disable feature

src/main/resources/modules-dependency-graph-template.html
=> feat(83): Modules Dependency Graph connection color feature

build.gradle.kts, docs/setup.md, src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPluginConfig.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/ScannerUtils.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/execution/BuildExecutionService.kt, src/test/kotlin/io/github/janbarari/gradle/analytics/scanner/BuildExecutionLogicTest.kt
> Feature-84
[Issue-52](https://github.com/janbarari/gradle-analytics-plugin/issues/52)
Tracking all branches feature added
Thanks to [alaegin](https://github.com/alaegin) for requesting feature 🧡
=> feat(84): Add tracking all branches feature

src/main/kotlin/io/github/janbarari/gradle/analytics/database/MySqlDatabaseConnection.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/database/SqliteDatabaseConnection.kt
> Fix-85
[Issue-89](https://github.com/janbarari/gradle-analytics-plugin/issues/89)
Issue #89 fixed
Thanks to [BarsukovNik](https://github.com/BarsukovNik) for sending bug report 🧡
=> fix(85): Fix issue #89

src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesbuildheatmap/report/RenderModulesBuildHeatmapReportStage.kt, src/main/resources/modules-dependency-graph-template.html
> Refactor-85
- Modules dependency graph color refactored
- Modules build heatmap colors refactored
=> refactor(85): Refactor modules build heatmap and modules dependency graph colors

.circleci/config.yml, build.gradle.kts
> Feature-89
Automate the publish process on main branch
=> feat(89): Add publish to Gradle portal task for CI

.circleci/config.yml
> Fix-90
Ci configuration duplicate job fixed
=> fix(90): Fix ci configuration duplicate job

docs/social-press.md, docs/upcoming-milestone.md, mkdocs.yml
> Noref-92
Social/Press and Upcoming Milestone will help the users to stay tuned about the plugin.
- `social/press` added
- `upcoming-milestone` added
- [ x] Is Detekt passed?
=> noref(92): Add `social-press` and `upcoming-milestone` in documentation

docs/upcoming-milestone.md, src/main/kotlin/io/github/janbarari/gradle/analytics/DatabaseConfig.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPluginConfig.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/report/RenderModulesDependencyGraphReportStage.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsInjector.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsTask.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/DependencyGraphGenerator.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/ScannerUtils.kt, src/main/resources/modules-dependency-graph-template.html, src/test/kotlin/io/github/janbarari/gradle/analytics/metric/modulesdependencygraph/report/RenderModulesDependencyGraphReportStageTest.kt, src/test/kotlin/io/github/janbarari/gradle/analytics/reporttask/ReportAnalyticsLogicTest.kt
> Feature-94
[RF-81](https://github.com/janbarari/gradle-analytics-plugin/issues/81)
- Added Request Feature 81
=> feat(94): Request Feature 81

docs/setup.md, src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPluginConfig.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/scanner/BuildScanner.kt
> Fix-95
There is a bug in the plugin configuration which leads to unsuccessful sync.
- Plugin configuration issue fixed
Tested on sample project with groovy
=> fix(95): Fix plugin configuration issue

docs/changelog.md, docs/setup.md
=> noref(97): Refactor documentation

src/main/kotlin/io/github/janbarari/gradle/analytics/GradleAnalyticsPlugin.kt
> Noref/98
- Plugin version updated in the plugin configuration
=> noref: Update plugin version in plugin configuration

detekt-config.yml, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/io/github/janbarari/gradle/analytics/data/DatabaseRepositoryImp.kt, src/main/kotlin/io/github/janbarari/gradle/analytics/database/Database.kt, src/test/kotlin/io/github/janbarari/gradle/utils/ProjectUtilsTest.kt
> Noref-99
Increase the plugin stability and support Gradle 8.1
- `kotlin` upgraded to `1.8.10`
- `detekt` upgraded to `1.23.0`
- `sqlite-driver` upgraded to `3.42.0.0`
- `mysql-driver` upgraded to `8.0.33`
- `jetbrains-exposed` upgraded to `0.41.1`
- `moshi` upgraded to `1.15.0`
- `commons-io` upgraded to `2.12.0`
- `mockk` upgraded to `1.13.5`
- `coroutines` upgraded to `1.7.1`
=> noref(99): Upgrade dependencies

docs/donation.md, docs/index.md
> Feat
- Added more donation address
=> feat: Add more donation addresses
